up:
	kubectl apply -f sample-deployment.yaml
	kubectl apply -f sample-service.yaml
	kubectl apply -f sample-ingress.yaml

down:
	kubectl delete -f sample-deployment.yaml
	kubectl delete -f sample-service.yaml
	kubectl delete -f sample-ingress.yaml

path:
	export PATH=$PATH:/snap/bin