kind: Namespace
apiVersion: v1
metadata:
  name: web
  labels:
    name: web
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
        - name: web-container
          image: ryutaterada/k8s-nodejs:1.1.9
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
          ports:
            - containerPort: 3000
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
      name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web
spec:
  backend:
    serviceName: web-service
    servicePort: 80
